apiVersion: authorization.openshift.io/v1
kind: RoleBinding
metadata:
  name: {{ include "metrics-collector.fullname" . }}
  labels:
    {{- include "metrics-collector.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
roleRef:
  name: {{ include "metrics-collector.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "metrics-collector.serviceAccountName" . }}