apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: ose-cli-with-jq
---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: ose-cli-with-jq
spec:
  source:
    type: Git
    git:
      uri: https://github.com/adamclark/metrics-collector
    contextDir: metrics-collector-image
  strategy:
    type: Docker                      
    dockerStrategy:
      dockerfilePath: Containerfile
  output:
    to:
      kind: ImageStreamTag
      name: 'ose-cli-with-jq:latest'